### ISSUE TITLE
Using NOPBC with FISST

### ISSUE THREAD

**Issue by aminsagar** [hocky-research-group/plumed-nest-eggs#1]
Hello. Thanks for making the FISST scripts available. I tried using FISST on my own system and I think something is not correct. This could be because I am using NOPBC with DISTANCE in PLUMED, but I am not sure. 
I am using the end-to-end distance as the CV and my input file looks like this.

```
UNITS LENGTH=A TIME=fs ENERGY=kcal/mol
MOLINFO STRUCTURE=step1_pdbreader.pdb
WHOLEMOLECULES ENTITY0=1-1600
b1: GROUP ATOMS=22
b2: GROUP ATOMS=1590
nc_a: GROUP ATOMS={444 444 444 444 444 455 968 968 455 968 968 455 455 968 968 968 455 455 906 906 906 947 906 935 935 935 654 654 654 466 466 466 482 496 496 482 496 513 532 513 532 532 532 961 513 961 961 961 961 666 666 666 666 666 626 626 640 640 640 146 146 146 166 166 180 180 561 551 551 561 561 585 597 585 585 5 22 194 194 194 194 381 393 409 381 393 393 421 421 437 437 437 1024 1043 1043 421 1024 1024 1043 1024 1043 1043 421 880 880 984 1000 880 984 1000 880 880 721 721 890 721 923 721 721 890 923 721 721 890 890 685 685 685 1365 355 366 366 355 355 366 366 1590 366 366 366 355 336 336 336 701 701 701 1295 1315 1295 1315 1295 1295 1315 1315 1315 1295 1315 1295 1315 1295 1326 1342 1326 1342 1342 1326 1342 1342 1326 1342 1353 1353 1382 1567 1567 1583 1583 1567 1567 1567 1583 1567 298 298 317 317 298 1531 1531 1531 1550 1550 317 1531 298 1531 1550 1550 211 231 1501 211 211 211 231 231 1501 1501 1501 231 1501 1455 114 114 126 1422 69 93 93 251 277 1086 840 840 840 805 816 816 860 805 816 805 805 805 816 805 1098 1117 1129 1153 1117 1117 1129 1129 1153 1098 795 795 795 728 746 728 746 1406 1204 1215 1230 1230 1215 1250 1264 1250 1250 1264 1517 1280 1280 780}
nc_b: GROUP ATOMS={466 421 1024 1000 409 968 906 947 482 482 496 984 1000 1000 513 890 437 1024 947 935 961 923 984 666 685 701 626 1353 685 1024 984 1000 513 532 961 984 984 961 961 180 146 166 180 701 551 935 890 923 984 640 1326 1342 1353 701 585 597 585 614 1353 180 551 561 551 126 211 231 597 114 126 114 126 614 69 114 126 39 55 251 263 166 231 409 421 437 355 355 366 1024 1043 1024 1043 1000 880 880 1000 1067 840 1067 840 860 816 860 1086 984 1000 890 890 805 860 860 840 728 890 923 923 685 685 1295 1315 701 701 1326 746 728 860 1326 1342 1353 1399 1590 1590 336 1567 1583 1567 1583 1567 1098 1117 1129 317 298 1531 1550 1315 1326 1342 1326 1342 1455 1455 728 746 728 1422 1406 1479 1280 1441 1441 1264 1353 1382 1422 114 1422 1406 1406 1399 1441 1365 1382 1399 1406 317 1531 317 1550 1204 1215 336 336 1129 1531 1550 1531 1550 211 1501 1215 1230 1215 1230 277 277 1517 1250 1517 1204 1501 1501 1455 251 263 277 263 277 277 1250 1264 1479 1280 1280 1422 69 93 1399 39 55 1399 277 1517 1117 1067 805 795 860 860 795 795 765 765 728 746 780 780 758 1129 1153 1204 1204 1168 1182 1168 1182 1182 1067 1264 758 765 1280 1280 758 765 1441 1168 1250 1264 1517 1182 1517 1517 1280 1479 1479 1479 1479 1441 758}

dend: DISTANCE ATOMS=b1,b2 NOPBC
nc:   COORDINATION GROUPA=nc_a GROUPB=nc_b  PAIR  D_0=7 R_0=0.5

#The conversion factor is 69.4786 pN = 1 kcal/mol/Angstrom

#0 pN to 100 pN
f: FISST MIN_FORCE=0.0 MAX_FORCE=1.44 PERIOD=200 NINTERPOLATE=31 ARG=dend OUT_RESTART=pull_fRange_fmin0_fmax100-d-nc-whole.restart-run3.txt OUT_OBSERVABLE=pull_fRange_fmin0_fmax100.observable-d-nc-whole-run3.txt OBSERVABLE_FREQ=1000 CENTER=0 RESTART_FMT=%e

PRINT ARG=dend,nc,f.dend_fbar,f.bias,f.force2 FILE=pull_fRange_fmin0_fmax100-d-nc-whole.colvar-run3.txt STRIDE=1000
```
However, when I plot the end-to-end distance after the simulation, the specified atoms don't seem to be getting pulled. Rather, in some simulations, they seem to be getting pushed towards each other. For example in the attached plot, the effect is quite apparent in one of the three simulations.
![image](https://user-images.githubusercontent.com/33936658/125601564-b4a222dd-a736-41e4-8465-7de7a7518c3d.png)

I see that in the ala pulling file, NOPBC has not been included in the DISTANCE action.
In my case the end-to-end distance is greater than half the simulation box. So, I wrap my protein and then compute the distance with NOPBC. Should this work? Am I missing something? 
I would be really grateful for any suggestions.
Thanks.
Amin.

**Comment by hockyg** [comment]
Hi Amin,

Thank you for your email. The script looks fine to me, it may be working
okay. As you hopefully saw from the paper, the idea of FISST is to sample
all the forces in the range that you specify, in your case, 0 to 100 pN.
That means that the system has to explore stretched and unstretched states
if that is to be the case. I think if you look at the observable file, and
it's working, you should see that these shorter end-end distances have more
weight in the columns for 0 force and less weight at 100 pN.

Do you know what the end-end distance should look like without FISST?

If you just want to see if it's working for stretching, you could also try
making the min force 90 and the max for 100.

Best
Glen

**Comment by aminsagar** [comment]
Thanks Prof. Hocky. You are right, the small end-to-end distances occur at 0 force. I was just concerned if I was handling the PBC conditions correctly. 
I get some frames with small end-to-end distance without FISST as well but I was expecting the force to switch quite rapidly to not allow consecutive appearance of such frames. But, after reweighting, I see that such frames are mainly populated at very low forces so everything makes sense.
Thanks for your response.
Amin.

**Comment by hockyg** [comment]
Okay, that sounds reasonable!

Just keep in mind that the force does not go up and down during the
simulation exactly, like in the method simulated tempering. It just depends
on the value of the collective variable and tries to ensure that “every
force” is sampled evenly, which can be a confusing concept.

We found it helpful to plot the quantity fbar versus time to see how it
looks.
In our experience, it never gets to the maximum or minimum force that you
select, however that is okay as far as I know.

Best,
Glen

**Comment by aminsagar** [comment]
It is indeed a bit difficult to grasp. But, I think I understand it to some extent.
I was actually getting a bit concerned about the values of fbar. I modified the script to have 5pN (0.072) as the minimum force and  50pN (0.72) as the maximum. The values of fbar look like this.
![image](https://user-images.githubusercontent.com/33936658/125972730-0914887a-d7f7-4fbe-8372-8de2842b1338.png)
As you said, it doesn't sample the highest values (or the lowest ones, but it gets close). How do you then assess if it is a problem or not? 
Does it make sense to aim for slightly larger values than desired to make sure that those points are sampled well?

**Comment by hockyg** [comment]
Yes exactly, it would make sense. We typically tried negative forces to
make sure 0 is covered.

However, besides that we’re still working on how to improve sampling for
cases where FISST alone does not allow the system to explore enough so I
don’t have a perfect solution yet.

**Comment by aminsagar** [comment]
Thanks a lot for your suggestions. It was very helpful.

Best,
Amin.
